### ISSUE TITLE
Cacher les emails des signataires

### ISSUE THREAD

**Issue by grimmlink** [MouvementY/y-website#22]
En regardant les signatures j'ai vu ca : 

![image](https://cloud.githubusercontent.com/assets/3241292/12422253/42dc9822-bec6-11e5-8e80-7ef7977fc5e4.png)

si pas de prénom et de nom alors l'email est affiché

**Comment by dulaccc** [comment]
Malheureusement, cette personne a utilisé son email dans le champ "prénom" :/ car j'ai bien son nom de famille dans le champ approprié.

J'ai corrigé ça, car effectivement cette personne a dû faire une erreur.

Merci pour ton retour @grimmlink.

**Comment by grimmlink** [comment]
ah en effet je n'ai pas pensé a ce scénario... PEBCAK comme on dit ^^

**Comment by dulaccc** [comment]
exactement ;)
